#!/usr/bin/env node
/**
 * build-abi.mjs — extract ABIs from forge `out/` into `dist/abi/`.
 *
 * Per-contract: writes `dist/abi/<Contract>.json` containing just the ABI
 * array (consumers want `abi`, not the full forge artifact). Also writes
 * `dist/abi/index.js` that re-exports every ABI as a named export so
 * consumers can do:
 *
 *   import { AgentAccount, DelegationManager } from '@agenticprimitives/contracts/abi';
 *
 * Closure: EXT3-001 (contracts as installable npm package).
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';

const ROOT = process.cwd();
const OUT = join(ROOT, 'out');
const DIST = join(ROOT, 'dist', 'abi');

if (!existsSync(OUT)) {
  console.error(`[build-abi] forge out/ missing — run \`forge build\` first.`);
  process.exit(1);
}

mkdirSync(DIST, { recursive: true });

// Include only contracts under src/ (skip lib/, test/, script/ artifacts).
const SRC_PREFIX = 'src/';

function isSourceContract(artifactPath) {
  // forge artifact path lives under out/<File>.sol/<Contract>.json
  // We can read the `metadata.sources` field; OR keep it simple and skip
  // common non-product names: forge-std (Test, Vm, console), OZ Tests, etc.
  const file = basename(artifactPath);
  if (/^Test|^Vm|^console/.test(file)) return false;
  return true;
}

const exports = [];

function walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else if (entry.isFile() && entry.name.endsWith('.json')) {
      if (!isSourceContract(full)) continue;
      let json;
      try {
        json = JSON.parse(readFileSync(full, 'utf8'));
      } catch {
        continue;
      }
      const sourcePath = json.ast?.absolutePath || json.metadata?.sources && Object.keys(json.metadata.sources)[0];
      if (!sourcePath || !sourcePath.startsWith(SRC_PREFIX)) continue;
      const abi = json.abi;
      if (!Array.isArray(abi)) continue;
      const name = entry.name.replace(/\.json$/, '');
      writeFileSync(join(DIST, `${name}.json`), JSON.stringify(abi, null, 2) + '\n');
      exports.push({ name, file: `${name}.json` });
    }
  }
}

walk(OUT);

exports.sort((a, b) => a.name.localeCompare(b.name));

const indexJs = [
  '// Generated by scripts/build-abi.mjs — do not edit by hand.',
  '// Each export is a viem-compatible ABI array.',
  '',
  ...exports.map((e) => `export { default as ${e.name} } from './${e.file}' with { type: 'json' };`),
  '',
].join('\n');

const indexDts = [
  '// Generated by scripts/build-abi.mjs — do not edit by hand.',
  "import type { Abi } from 'viem';",
  '',
  ...exports.map((e) => `export declare const ${e.name}: Abi;`),
  '',
].join('\n');

writeFileSync(join(DIST, 'index.js'), indexJs);
writeFileSync(join(DIST, 'index.d.ts'), indexDts);

console.log(`[build-abi] wrote ${exports.length} ABI(s) to dist/abi/`);
