/**
 * Playwright config for agenticprimitives demo E2E tests — all-Cloudflare.
 *
 * Each spec file under specs/ is an isolated feature test, runnable on its own:
 *   pnpm test -- 01-demo-user
 *   pnpm test:ui -- 02-siwe-login
 *
 * webServer chain:
 *   anvil → globalSetup (deploy + gen-dev-vars + d1 migrate)
 *   → wrangler dev for demo-a2a Worker (port 8787)
 *   → wrangler dev for demo-mcp Worker (port 8788)
 *   → vite for demo-web (port 5173, proxies /a2a/* to Worker)
 *
 * Wrangler reads .dev.vars files (created by gen-dev-vars.ts) for secrets +
 * contract addresses, so no env injection is needed here beyond Vite's.
 */
import { defineConfig, devices } from '@playwright/test';

const REPO_ROOT = new URL('../..', import.meta.url).pathname;

const VITE_ENV: Record<string, string> = {
  VITE_CHAIN_ID: '31337',
};

export default defineConfig({
  testDir: './specs',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: 1,
  reporter: process.env.CI ? [['list'], ['html', { open: 'never' }]] : 'list',

  use: {
    // Use `localhost` (not 127.0.0.1) so WebAuthn accepts the
    // origin's effective domain as a valid rp.id. WebAuthn rejects
    // IP addresses as relying-party identifiers; only hostnames are
    // permitted (with `localhost` as a special exception).
    baseURL: 'http://localhost:5173',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  webServer: [
    // 1. Anvil — local chain.
    {
      command: 'anvil --port 8545 --silent',
      url: 'http://127.0.0.1:8545',
      reuseExistingServer: !process.env.CI,
      timeout: 30_000,
    },
    // 2. demo-a2a Worker. wrangler dev reads .dev.vars (generated by global-setup).
    //    Workers refresh on source changes; reuseExistingServer:false guarantees
    //    a clean state for each test run.
    {
      command: 'pnpm --filter @agenticprimitives-demo/a2a dev',
      url: 'http://127.0.0.1:8787/health',
      reuseExistingServer: false,
      timeout: 90_000,
      cwd: REPO_ROOT,
    },
    // 3. demo-mcp Worker.
    {
      command: 'pnpm --filter @agenticprimitives-demo/mcp dev',
      url: 'http://127.0.0.1:8788/health',
      reuseExistingServer: false,
      timeout: 90_000,
      cwd: REPO_ROOT,
    },
    // 4. demo-web (Vite) — proxies /a2a/* to demo-a2a Worker.
    {
      command: 'pnpm --filter @agenticprimitives-demo/web dev',
      url: 'http://127.0.0.1:5173',
      reuseExistingServer: !process.env.CI,
      timeout: 60_000,
      env: VITE_ENV,
      cwd: REPO_ROOT,
    },
  ],

  globalSetup: './helpers/global-setup.ts',
});
