// Shared types for @agenticprimitives/connect-auth.

import type { Address, Hex } from '@agenticprimitives/types';

export type { Address, Hex };

export type AuthMethod = 'passkey' | 'siwe' | 'google';

export interface JwtClaims {
  sub: string;
  walletAddress: Address | null;
  smartAccountAddress: Address;
  name: string;
  email: string | null;
  via: AuthMethod;
  kind: 'session' | 'session-grant';
  iat: number;
  exp: number;
  /**
   * R5.10 / PKG-CONNECT-AUTH-003 (external audit P1-1).
   *
   * `iss` (issuer) — the origin / canonical URI of the Connect broker
   * that minted this session. Verifiers MUST cross-check
   * `claims.iss === expectedIss` to prevent a cookie minted by a
   * different broker (or a malicious broker on a sibling origin) from
   * authenticating against this app.
   *
   * `aud` (audience) — the relying app(s) this cookie is valid for.
   * May be a single origin/URI or an array. Verifiers MUST cross-check
   * `expectedAud` is in `claims.aud` so a session minted for app A
   * cannot be replayed at app B even when both share the broker.
   *
   * `sid` (session id) — a high-entropy id for this specific session.
   * Lets the broker revoke a single session (by adding `sid` to a
   * revocation list) without invalidating all sessions for `sub`.
   * Auto-generated by `mintSession` when not supplied by the caller.
   *
   * `nonce` — optional OIDC-style replay nonce, threaded through from
   * an upstream authorize request when this cookie carries one.
   */
  iss: string;
  aud: string | string[];
  sid: string;
  nonce?: string;
}

export interface AuthenticatedUser {
  id: string;
  walletAddress: Address | null;
  smartAccountAddress: Address | null;
  name: string;
  email: string | null;
  via: AuthMethod;
}

export interface TypedDataDomain {
  name?: string;
  version?: string;
  chainId?: number;
  verifyingContract?: Address;
  salt?: Hex;
}

export type TypedDataTypes = Record<string, Array<{ name: string; type: string }>>;

export interface Signer {
  readonly address: Address;
  signMessage(msg: string | { raw: Hex }): Promise<Hex>;
  signTypedData(args: {
    domain: TypedDataDomain;
    types: TypedDataTypes;
    primaryType: string;
    message: Record<string, unknown>;
  }): Promise<Hex>;
}

export interface PasskeyAssertion {
  authenticatorData: Hex;
  clientDataJSON: Hex;
  signature: Hex;
}

export interface PasskeySigner extends Signer {
  readonly credentialId: string;
  assert(challenge: Hex): Promise<PasskeyAssertion>;
}

export interface EOASigner extends Signer {
  /** marker type — viem-compatible LocalAccount or WalletClient adapter */
}

export interface KMSSigner extends Signer {
  readonly keyId: string;
  readonly provider: 'local-aes' | 'aws-kms' | 'gcp-kms';
}
