// Spec 207 threshold-policy + quorum utilities.
//
// `packSafeSignatures` produces the Safe-compatible 65-byte-per-slot
// signature blob that both `QuorumEnforcer.beforeHook` (caveat path)
// and `AgentAccount._verifyQuorum` (admin/recovery path) expect.
// `computeAdminPayloadHash` mirrors `AgentAccount._adminPayloadHash`
// off-chain so SDK callers can derive the digest they need to sign
// without a chain round-trip.
//
// Both utilities are pure — no providers, no chain reads. The
// `AgentAccountClient` admin methods use them internally; consumers
// who want to build their own admin tooling can import them directly.

import {
  encodeAbiParameters,
  encodePacked,
  keccak256,
  type Address,
  type Hex,
} from 'viem';

// ─── Signature slot packing ──────────────────────────────────────────

/**
 * One slot in the Safe-compatible packed signature blob. Each slot is
 * 65 bytes: `{32 r}{32 s}{1 v}`. The `v` byte discriminates the
 * verification path per spec 207 § 5 (see SignatureSlotRecovery):
 *
 *   v ∈ {27, 28}  → ECDSA over the raw payload hash
 *   v > 30        → eth_sign / EIP-191-wrapped ECDSA (v - 4 = recovery)
 *   v == 1        → pre-approved hash; `r` holds the signer
 *                   (left-padded), `s` unused
 *   v == 0        → ERC-1271 contract sig; `r` holds signer
 *                   (left-padded), `s` holds the byte offset into the
 *                   blob where the length-prefixed dynamic sig tail
 *                   starts. (Not generated by this helper today —
 *                   build the blob manually if you need this path.)
 */
export interface SafeSignatureSlot {
  /** Address that signed (or the contract address for v=0). */
  signer: Address;
  /** Raw 65-byte ECDSA signature `{r}{s}{v}` from `viem.sign` or
   *  `vm.sign`. The packer extracts the (r, s, v) bytes and writes
   *  them into the appropriate slot ordering after sort. */
  signature: Hex;
}

/**
 * Pack signature slots into Safe's `checkSignatures` blob format
 * (sorted-ascending by signer address — the anti-duplicate scheme).
 *
 * Caller MUST provide slots whose `signature` bytes are 65-byte ECDSA
 * (r/s/v). The packer doesn't re-sign — it just sorts + concatenates.
 * For non-ECDSA slot types (v=0 ERC-1271 with a dynamic tail; v=1
 * pre-approved hash), build the blob via `encodePacked` directly with
 * the per-slot conventions documented in `SafeSignatureSlot.v`.
 */
export function packSafeSignatures(slots: SafeSignatureSlot[]): Hex {
  if (slots.length === 0) {
    throw new Error('packSafeSignatures: at least one slot required');
  }
  // Validate sig shapes before sorting.
  for (const s of slots) {
    const bytes = s.signature.startsWith('0x') ? s.signature.slice(2) : s.signature;
    if (bytes.length !== 130) {
      throw new Error(
        `packSafeSignatures: signature for ${s.signer} must be 65 bytes (130 hex chars); got ${bytes.length}`,
      );
    }
  }
  // Sort ascending by signer address (case-insensitive — addresses are
  // sometimes mixed-case via checksum normalisation).
  const sorted = [...slots].sort((a, b) =>
    a.signer.toLowerCase() < b.signer.toLowerCase() ? -1 : 1,
  );
  // Reject duplicate signers — the on-chain verifier would catch this
  // anyway, but failing early is friendlier.
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i]!.signer.toLowerCase() === sorted[i - 1]!.signer.toLowerCase()) {
      throw new Error(`packSafeSignatures: duplicate signer ${sorted[i]!.signer}`);
    }
  }
  let out = '0x';
  for (const s of sorted) {
    out += s.signature.replace(/^0x/, '');
  }
  return out as Hex;
}

// ─── Admin payload-hash derivation ───────────────────────────────────

/**
 * Verbs used in `AgentAccount._adminPayloadHash` (apps/contracts/src/
 * AgentAccount.sol). Bound to the payload alongside (proposalId,
 * action, args, eta, address, chainid) so a propose sig can't be
 * replayed as an execute sig + sigs don't cross-replay between
 * accounts or chains.
 */
export const ADMIN_VERB_PROPOSE: Hex = '0x41444d494e5f50524f504f5345' as const;  // bytes32("ADMIN_PROPOSE") — viem encodes properly
export const ADMIN_VERB_EXECUTE: Hex = '0x41444d494e5f455845435554' as const;     // bytes32("ADMIN_EXECUTE")
export const ADMIN_VERB_CANCEL: Hex  = '0x41444d494e5f43414e43454c' as const;     // bytes32("ADMIN_CANCEL")

/**
 * Match `AgentAccount._adminPayloadHash` exactly. Verbs are
 * `bytes32("ADMIN_PROPOSE" | "ADMIN_EXECUTE" | "ADMIN_CANCEL")` —
 * use the `ADMIN_VERB_*` constants below, NOT raw strings, because
 * `bytes32(stringLiteral)` packs from the LEFT in Solidity and the
 * SDK must match the exact byte layout.
 */
export function computeAdminPayloadHash(args: {
  verb: 'PROPOSE' | 'EXECUTE' | 'CANCEL';
  proposalId: bigint;
  action: number;
  callArgs: Hex;
  eta: bigint;
  account: Address;
  chainId: bigint;
}): Hex {
  // bytes32(string) in Solidity: left-justified, zero-padded right.
  // Compute via encodePacked + hex-padding.
  const verbBytes = new TextEncoder().encode(`ADMIN_${args.verb}`);
  if (verbBytes.length > 32) {
    throw new Error(`computeAdminPayloadHash: verb too long: ADMIN_${args.verb}`);
  }
  const padded = new Uint8Array(32);
  padded.set(verbBytes, 0);
  let verbHex = '0x';
  for (const b of padded) verbHex += b.toString(16).padStart(2, '0');

  const callArgsHash = keccak256(args.callArgs);

  return keccak256(
    encodeAbiParameters(
      [
        { type: 'bytes32' }, // verb
        { type: 'uint256' }, // proposalId
        { type: 'uint8' },   // action
        { type: 'bytes32' }, // keccak256(args)
        { type: 'uint64' },  // eta
        { type: 'address' }, // address(account)
        { type: 'uint256' }, // chainId
      ],
      [
        verbHex as Hex,
        args.proposalId,
        args.action,
        callArgsHash,
        args.eta,
        args.account,
        args.chainId,
      ],
    ),
  );
}

// Suppress unused-import warning while the encodePacked path stays
// reserved for future v=0 / v=1 slot helpers.
void encodePacked;
