/**
 * gen-dev-vars.ts
 *
 * Reads apps/contracts/deployments-<network>.json (written by the forge
 * deploy script) and emits .dev.vars files for the demo Workers so
 * `wrangler dev` picks up the right contract addresses + secrets without
 * hand-editing files.
 *
 * Usage:
 *   tsx scripts/gen-dev-vars.ts                    # network=anvil
 *   DEPLOY_NETWORK=base-sepolia tsx scripts/gen-dev-vars.ts
 *
 * Generated files:
 *   apps/demo-a2a/.dev.vars
 *   apps/demo-mcp/.dev.vars
 *
 * Both files are gitignored — they hold dev-only secrets too.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const REPO_ROOT = join(import.meta.dirname ?? __dirname, '..');
const NETWORK = process.env.DEPLOY_NETWORK ?? 'anvil';
const DEPLOYMENTS_PATH = join(REPO_ROOT, 'apps', 'contracts', `deployments-${NETWORK}.json`);

if (!existsSync(DEPLOYMENTS_PATH)) {
  console.error(`gen-dev-vars: ${DEPLOYMENTS_PATH} not found.`);
  console.error('Run `pnpm dev:contracts` (or your deploy script) first.');
  process.exit(1);
}

interface Deployments {
  chainId: number;
  entryPoint: string;
  delegationManager: string;
  agentAccountFactory: string;
  timestampEnforcer: string;
  allowedTargetsEnforcer: string;
  allowedMethodsEnforcer: string;
  valueEnforcer: string;
  smartAgentPaymaster?: string;
  universalSignatureValidator?: string;
}

const d = JSON.parse(readFileSync(DEPLOYMENTS_PATH, 'utf8')) as Deployments;

// Dev-only secrets. Stable across runs so cookies + AAD-bound encryption
// don't break when wrangler restarts. NEVER use these in production —
// production sets via `wrangler secret put`.
const DEV_SECRETS = {
  SESSION_JWT_SECRETS: 'e2e-kid:' + 'aa'.repeat(32),
  CSRF_SECRET: '0x' + 'bb'.repeat(32),
  A2A_SESSION_SECRET: '0x' + 'cc'.repeat(32),
  // Anvil[0] private key. Public knowledge; safe for dev.
  A2A_MASTER_PRIVATE_KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
};

function writeDotEnv(filePath: string, content: Record<string, string>): void {
  const lines = ['# Generated by scripts/gen-dev-vars.ts — DO NOT EDIT BY HAND'];
  lines.push(`# Source: deployments-${NETWORK}.json`);
  lines.push('');
  for (const [k, v] of Object.entries(content)) {
    lines.push(`${k}=${v}`);
  }
  writeFileSync(filePath, lines.join('\n') + '\n', 'utf8');
}

const a2aVars: Record<string, string> = {
  ...DEV_SECRETS,
  ENTRY_POINT: d.entryPoint,
  DELEGATION_MANAGER: d.delegationManager,
  AGENT_ACCOUNT_FACTORY: d.agentAccountFactory,
  TIMESTAMP_ENFORCER: d.timestampEnforcer,
  ALLOWED_TARGETS_ENFORCER: d.allowedTargetsEnforcer,
  ALLOWED_METHODS_ENFORCER: d.allowedMethodsEnforcer,
  VALUE_ENFORCER: d.valueEnforcer,
  // PAYMASTER: only present when deployments JSON has the address.
  // Without it, demo-a2a's /session/deploy returns 409 and the frontend
  // falls back to counterfactual mode.
  ...(d.smartAgentPaymaster ? { PAYMASTER: d.smartAgentPaymaster } : {}),
  // UNIVERSAL_SIGNATURE_VALIDATOR: only present when deployments JSON
  // has it. Without it, /auth/siwe-verify falls back to ECDSA-only
  // recovery (EOA flow); passkey login will fail.
  ...(d.universalSignatureValidator
    ? { UNIVERSAL_SIGNATURE_VALIDATOR: d.universalSignatureValidator }
    : {}),
};

const mcpVars: Record<string, string> = {
  DELEGATION_MANAGER: d.delegationManager,
  TIMESTAMP_ENFORCER: d.timestampEnforcer,
  ALLOWED_TARGETS_ENFORCER: d.allowedTargetsEnforcer,
  ALLOWED_METHODS_ENFORCER: d.allowedMethodsEnforcer,
  VALUE_ENFORCER: d.valueEnforcer,
};

writeDotEnv(join(REPO_ROOT, 'apps', 'demo-a2a', '.dev.vars'), a2aVars);
writeDotEnv(join(REPO_ROOT, 'apps', 'demo-mcp', '.dev.vars'), mcpVars);

console.log(`gen-dev-vars: wrote .dev.vars for demo-a2a + demo-mcp (network=${NETWORK})`);
console.log(`  factory: ${d.agentAccountFactory}`);
console.log(`  delegationManager: ${d.delegationManager}`);
